name: 'React Native Bundle Analyzer'
description: 'Compare bundles between pull requests'
author: 'sarfraz'

inputs: 
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  TYPE:
    description: 'Type of Function'
    required: true
  BRANCH_NAME:
    description: 'Branch Name'

runs:
  using: 'node20'
  main: 'dist/index.js'
