name: 'React Native Bundle Analyzer'
description: 'Compare bundles between pull requests'
author: 'sarfraz'

inputs: 
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  TYPE:
    description: 'Type of Function'
    required: true
  BRANCH_NAME:
    description: 'Branch Name'
  BRANCH_TO: 
    description: 'Branch To'
  EXCLUDE:  
    description: 'File Exlusions'


runs:
  using: 'node16'
  main: 'dist/index.js'
